### ISSUE TITLE
Stark_s & Start_st

### ISSUE THREAD

**Issue by vongocminh778** [l-sf/Track-trt#3]
Thank you for your amazing repo, in the old version, I saw that you switched to the stark model. Could you provide a tutorial on how to switch to stark_s and stark_st?

**Comment by l-sf** [comment]
Thank you for your interest in this repo, I'm sorry for your request. 
Indeed, I had planned to deploy Stark. but I didn't finish it, because during the deployment process, I found that the mask of the Stark model was difficult to handle in Tensorrt, and the search branch had a lot of input, making it difficult to process. So I chose the ostrack with a more concise model and the lighttrack with a lighter weight.

**Comment by vongocminh778** [comment]
Thank you for your efforts and the excellence of this repo, hoping for even better tracking in the future.
