### ISSUE TITLE
Template refreshing (Question)

### ISSUE THREAD

**Issue by arielkantorovich** [l-sf/Track-trt#6]
Hi, I want to know more details on the template image that is input to the network. I understand that you implemented init method that gets ROI from the user, my question is if you refrese the template image for example any 5 frames or it's always the same template (from ROI)?
moreover how I can control the template that gets into the network because, in the tracking method, you only input the current frame.

I want to say thank you for a great project I started to dive into details and I want to understand more your code.
wise you the Best. :)

**Comment by l-sf** [comment]
According to the papers of LightTrack and OSTrack, template images are only initialized in the first frame of the image sequence, and subsequent image frames are search images. This paradigm is defined by a series of one-shot-tracking papers.

The essence of single-object tracking is to compare the similarity between the tracked target and the search image region, and the higher the similarity, the more likely it is to be a tracked target. Because the ROI of the first frame is the most accurate target feature, subsequent tracked features will be contaminated by the background. Therefore, when performing feature related calculations, the ROI of the first frame is always used, which is defined by siamese-tracking.

STARK-ST and MixFormer use subsequent frames for cross attention calculation, updating every 200 frames, but the computation is very very large and not suitable for deployment.

**Comment by arielkantorovich** [comment]
Thank you for the great answer,
Still, something missing because (in my opinion) if I track some object there is an option that after a "long time" let's say 150 frames the object changes its appearance it can happen for a lot of reasons for example let's say that my camera can move, so there is some motivation sometimes to update the template by "new" bbox that I get from the NN (encourage Markov assumption).
In this case I need again use the init method ?

**Comment by l-sf** [comment]
You are right. These tracking methods are fine for short-term tracking, but long-term tracking can lead to object feature changes, which may cause tracking problems. Whether or not it can be successfully tracked depends on the specific situation. 
If it does fail, it is possible to modify the program and reinitialize template. However, this may require you to design the logic yourself, such as how to determine tracking failure and when to reinitialize the template. 
In my drone tracking people scenario, it can track successfully all the time.

Best wishes.
